#!/bin/bash
#SBATCH -n 20
#SBATCH --mem-per-cpu=2048
#SBATCH --time=2-23:59:59
#SBATCH --mincpus=32
#SBATCH --mail-user=hitesh.goel@research.iiit.ac.in
#SBATCH --mail-type=ALL
#SBATCH --gres=gpu:4
#SBATCH --output inf_baseline.log

module add cuda/8.0
module add cudnn/7-cuda-8.0

export CUDA_VISIBLE_DEVICES=0,1,2,3

time python3 t2t.py --job $1 --lang $2 --mission $3 --mark $4 --gaussian $5 --orz noisy
